# Generated by Django 4.2.5 on 2023-09-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigei', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sigei',
            name='image',
        ),
        migrations.AlterField(
            model_name='sigei',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
